#!/bin/sh
#
# A hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# praw.ini should never be committed, only kept as a template file
# in the remote repo
echo "The praw.ini will not be comitted."
echo "To fix this go to the file .githooks/pre-commit but this\nnot advised."
exec git reset -- praw.ini
